M48
; DRILL file {KiCad (6.0.11)} date Wed 01 Feb 2023 09:23:00 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-01T21:23:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
%
G90
G05
T1
X5.4603Y-1.9462
X5.4603Y-2.1738
T2
X5.3056Y-2.415
X5.4138Y-2.415
T0
M30
