M48
; DRILL file {KiCad (6.0.11)} date Thu 02 Feb 2023 02:22:04 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-02T14:22:04-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
%
G90
G05
T1
X3.4288Y-1.6748
X3.4288Y-1.9023
T2
X3.274Y-2.1435
X3.3823Y-2.1435
T0
M30
